function loadGame(gameSessionId){
    getAliveEnemy(gameSessionId);
    getDeadPlayer(gameSessionId);
    getAliveEnemy(gameSessionId);
    getDeadEnemy(gameSessionId);
    getAliveCharacterDetail(gameSessionId);
    getDeadCharacterDetail(gameSessionId);
    getAliveEnemyDetail(gameSessionId);
    getDeadEnemyDetail(gameSessionId);
    getInventory(gameSessionId);
    getItemInInventory(gameSessionId);
    getItemPool();
    displayIcon('enemy-inside',enemySrc);
    displayIcon('char-1-inside',char1Src);
    displayIcon('char-2-inside',char2Src);
    displayIcon('char-3-inside',char3Src);
    displayIcon('char-4-inside',char4Src);
    displayInventory(inventoryList,itemInInventoryList);
}